import React, { useState } from 'react';
import { Sparkles, Loader2, RefreshCw } from 'lucide-react';
import { generateDreamFlavor } from '../services/geminiService';
import { AiFlavorResponse } from '../types';

export const AiFlavorLab: React.FC = () => {
  const [inspiration, setInspiration] = useState('');
  const [flavor, setFlavor] = useState<AiFlavorResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inspiration.trim()) return;

    setLoading(true);
    setError('');
    setFlavor(null);

    try {
      const result = await generateDreamFlavor(inspiration);
      if (result) {
        setFlavor(result);
      } else {
        setError("Our Moo-bot is having a break. Try again!");
      }
    } catch (err) {
      setError("Something went wrong in the mixing lab.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-sweetPink/10 py-16 px-4">
      <div className="max-w-4xl mx-auto text-center">
        <span className="inline-block p-3 rounded-full bg-sweetPink/20 text-sweetPink mb-4">
            <Sparkles size={32} />
        </span>
        <h2 className="text-4xl font-display font-bold text-gray-900 mb-4">Sweet Cow Dream Lab</h2>
        <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto font-sans">
          Tell our AI what you're craving (e.g., "a rainy day in London" or "spicy mango fiesta") and we'll invent a custom flavor just for you!
        </p>

        <form onSubmit={handleGenerate} className="flex flex-col sm:flex-row gap-4 justify-center max-w-lg mx-auto mb-12">
            <input
                type="text"
                value={inspiration}
                onChange={(e) => setInspiration(e.target.value)}
                placeholder="Enter your inspiration..."
                className="flex-1 px-6 py-4 rounded-full border-2 border-sweetPink/30 focus:border-sweetPink outline-none shadow-sm text-lg font-sans"
            />
            <button 
                type="submit"
                disabled={loading || !inspiration}
                className="px-8 py-4 bg-sweetPink hover:bg-pink-400 disabled:bg-pink-200 text-white rounded-full font-bold text-lg shadow-lg transition-all flex items-center justify-center gap-2 font-display"
            >
                {loading ? <Loader2 className="animate-spin" /> : 'Churn It!'}
            </button>
        </form>

        {error && <p className="text-red-500 font-bold mb-8">{error}</p>}

        {flavor && (
          <div className="bg-white rounded-3xl shadow-xl overflow-hidden border-4 border-sweetPink/20 transform transition-all animate-fade-in-up">
            <div className="h-32 w-full relative" style={{ backgroundColor: flavor.colorHex }}>
                <div className="absolute inset-0 flex items-center justify-center opacity-20 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')]"></div>
            </div>
            <div className="p-8 -mt-12 relative z-10">
                <div className="inline-block bg-white p-4 rounded-full shadow-lg mb-4">
                     <div className="w-16 h-16 rounded-full" style={{ backgroundColor: flavor.colorHex }}></div>
                </div>
                <h3 className="text-3xl font-bold text-gray-900 mb-2 font-display">{flavor.flavorName}</h3>
                <p className="text-lg text-gray-600 mb-6 italic font-serif">"{flavor.description}"</p>
                
                <div className="bg-sweetCream p-6 rounded-2xl">
                    <h4 className="font-bold text-gray-800 mb-3 uppercase tracking-wide text-sm">Ingredients</h4>
                    <div className="flex flex-wrap gap-2 justify-center">
                        {flavor.ingredients.map((ing, i) => (
                            <span key={i} className="px-3 py-1 bg-white border border-gray-200 rounded-full text-gray-700 text-sm">
                                {ing}
                            </span>
                        ))}
                    </div>
                </div>
                
                <div className="mt-8 pt-6 border-t border-gray-100">
                    <p className="text-sm text-gray-400">Generated by Gemini • Sweet Cow Dream Lab</p>
                </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
